apiVersion: v1
kind: Secret
metadata:
  name: {{ include "copilot.fullname" . }}
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
type: Opaque
