apiVersion: v1
kind: Service
metadata:
  name: {{ include "copilot.fullname" . }}
  labels:
    {{- include "copilot.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "copilot.selectorLabels" . | nindent 4 }}
